### ISSUE TITLE
Refactor base-sql to use built-in pgp helpers

### ISSUE THREAD

**Issue by vitaly-t** [jmeas/api-pls#40]
Consider the methods in the [helpers](http://vitaly-t.github.io/pg-promise/helpers.html) namespace as a better way of generating inserts and updates, especially when one needs multi-row updates and multi-row inserts.

See also:

* http://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise
* http://stackoverflow.com/questions/39119922/postgresql-multi-row-updates-in-node-js

**Comment by jmeas** [comment]
Very cool. I'll check these out. Thanks!

**Comment by jmeas** [comment]
Renamed the issue so I can better track it. Looks like I'll be able to clean up [base-sql.js](https://github.com/jmeas/api-pls/blob/master/server/util/base-sql.js) quite a bit using these. Also, these helpers seem powerful enough for the other features I plan to add to the Controller.

**Comment by jmeas** [comment]
@vitaly-t , I'm updating this library to handle more complex queries. These are going to be a huge help, and they're going to save me a lot of time and headaches. Thanks for the great suggestion.
