### ISSUE TITLE
Allow SSL to be optional

### ISSUE THREAD

**Issue by ericvaladas** [jmeas/api-pls#44]
I use Postgres.app for local development and it does not have SSL enabled out of the box. It looks like the database config appends `?ssl=true` for us, but it would be nice if we could have control over that parameter. Maybe we could include the `ssl` parameter in our `DATABASE_URL` variable so that we have control over whether SSL is used in our environments.

**Comment by jmeas** [comment]
This is a great idea. I think there was some use case where I needed SSL, and then another where it would blow up if I included SSL, which led to the particular (admittedly weird) configuration. I'll take a look and see if I can make this more predictable, and update the docs, too.

thanx for da issue
